logging:
  level:
    io.r2dbc.h2: TRACE

spring:
  application:
    name: notes

  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: 1303402323602702477
            client-secret: KkSr58xUWK0KSaSyXnSgyrM6qoqP920a
            scope: identify, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/discord"
            client-authentication-method: client_secret_post
            client-name: Discord
            provider: discord
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username

  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    initialization-mode: always

  h2:
    console:
      enabled: true

server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    contextPath: /api

jwt:
  secret_key: 9Xqfvh14tls3TA/ush4ZcUS/61qlon/3/Dfg9qt/EPqIYGTLvbJn2GW44hd7BFMjvrDxoPiEf9Uod0Kd4T7k5w==
  expiration: 900000
  refresh_expiration: 86400000

auth:
  cookie:
    domain: localhost
    path: /
    name:
      access_token: access_token
      refresh_token: refresh_token

  success_uri: http://localhost/success