spring:
  application:
    name: notes

  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            scope: identify, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/discord"
            client-authentication-method: client_secret_post
            client-name: Discord
            provider: discord
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: "${PORT}"
  forward-headers-strategy: framework
  servlet:
    contextPath: /api

jwt:
  secret_key: ${JWT_SECRET}
  access_lifetime: PT1M
  refresh_lifetime: P1D

auth:
  cookie:
    domain: ${DOMAIN}
    path: /
    name:
      access_token: access_token
      refresh_token: refresh_token

  success_uri: ${URL_REDIRECT_SUCCESS}